# Mission 1

Below is a dictionary containing the number of French campuses that offer each kind of Wild Code School course.

wildcodeschool = {
   "data_analyst": 4,
   "data_scientist": 2,
   "dev_web": "13"
}

Find a way to only display the keys that have int values.

In [ ]:
wildcodeschool =	{
  "data_analyst": 4,
  "data_scientist": 2,
  "dev_web": 13}

cles = list(wildcodeschool.items())
vide = []

for i, j in wildcodeschool.items():
  if isinstance(j, int) == True:
    vide.append(i)
print(vide)

['data_analyst', 'data_scientist', 'dev_web']

# Mission 2

For the same dictionary, find a way to display all the values that have a key that contains the letter "e".

In [22]:
for key, value in wildcodeschool.items():
  if "e" in key:
    print(value)

2
13

# Mission 3

Within the same dictionary, change the type of the value of the "dev_web" key to be an int. Then add a new key-value pair which will be "total_campus" : 19, using a **dictionary method**.

**Change the value of "dev_web" to be and int :**

In [ ]:
# We will use the int() function for that

wildcodeschool =	{
  "data_analyst": 4,
  "data_scientist": 2,
  "dev_web": 13}

**Add a new key-value pair which will be "total_campus" : 19, using a dictionary method**

In [ ]:
## Method 1
# We will add a new key-value pair to the dictionary using the update() method which is a dictionary method

wildcodeschool.update({"total_campus" : 19})
print(wildcodeschool)

In [ ]:
## Method 2
# We can also create a new key-value pair using the following method

wildcodeschool =	{
  "data_analyst": 4,
  "data_scientist": 2,
  "dev_web": 13}

wildcodeschool["total_campus"] = 19
print(wildcodeschool)

{'data_analyst': 4, 'data_scientist': 2, 'dev_web': 13, 'total_campus': 19}

# Mission 4

Take the dictionary generated from mission 3. Delete the key value pair :
- 'dev_web': 13 using a method
- 'total_campus': 19 using another method

In [ ]:
wildcodeschool = {'data_analyst': 4, 'data_scientist': 2, 'dev_web': 13, 'total_campus': 19}

wildcodeschool.pop('dev_web')
print(wildcodeschool)

wildcodeschool.clear()
wildcodeschool.update({'data_analyst': 4, 'data_scientist': 2})
print(wildcodeschool)

{'data_analyst': 4, 'data_scientist': 2, 'total_campus': 19}
{'data_analyst': 4, 'data_scientist': 2}

# Mission 5

Still within the dictionary generated from Mission 3, find a way to display the dictionary keys in alphabetical order.

In [ ]:
wildcodeschool = {'data_analyst': 4, 'data_scientist': 2, 'dev_web': 13, 'total_campus': 19}

sorted(wildcodeschool.keys())

['data_analyst', 'data_scientist', 'dev_web', 'total_campus']

# Mission 6

Create a script that returns the same elements as the **values()** method, as a list.

Example: for `{'a': 1, 'b': 2, 'c': 3}` it will create `[1, 2, 3]`

In [ ]:
wildcodeschool = {'data_analyst': 4, 'data_scientist': 2, 'dev_web': 13, 'total_campus': 19}

liste_valeurs = []

for i in wildcodeschool.values():
  liste_valeurs.append(i)
print(liste_valeurs)

[4, 2, 13, 19]